# Generated by Django 4.0.5 on 2022-11-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=32)),
                ('img_path', models.CharField(max_length=32)),
                ('data', models.ImageField(upload_to='static/notedata')),
            ],
        ),
    ]
